### PR TITLE
Fix invalid forms

### LINKED ISSUE #292: Multiple <input>-tags in one <label>-tag is invalid HTML
With multi-fields of some types (e.g. color) there will be multiple `<input>`-tags within a single `<label>`-tag. This is not valid HTML.

However, I am currently not sure how to solve this nicely.

### PR DESCRIPTION
**Pull request by micgro42**
Multiple inputs within a single label are invalid HTML. This bug can not only occur in multi-fields, but also in plugin-provided single fields which may contain multiple input-fields, which are then combined by JavaScript.

Thus, we provide an id which every type can assign to the edit-field best suited. For multi-types this is usually the new-input-template.

Fixes #292

----
##### semi-related sidenote:
I noted that the functions `\action_plugin_struct_entry::createForm` and `\action_plugin_struct_entry::makeField` are exact copies of `\action_plugin_struct_edit::createForm` and `\action_plugin_struct_edit::makeField`. Also `\action_plugin_struct_entry::createForm` is apparently only used in tests . Method `\action_plugin_struct_entry::makeField` is also used for lookups, but couldn't that use the functionality of `\action_plugin_struct_edit::makeField`? Or am I missing something?

(This should probably be fixed before this is merged)

### CODE REVIEW

File: types/Checkbox.php [hunk 1]
```diff
@@ -62,8 +67,11 @@ public function multiValueEditor($name, $rawvalues) {
                 $checked = '';
             }
 
+            $id = !empty($htmlID) ? "id=\"$htmlID\"" : '';
+            $htmlID = null;
```
Comment (splitbrain) [inline types/Checkbox.php]: Why the assignment to `$htmlID` here? It's not passed by reference and not used anymore further down the function?

File: types/Color.php [hunk 2]
```diff
@@ -56,15 +56,16 @@ public function renderMultiValue($values, \Doku_Renderer $R, $mode) {
...
         $class = 'struct_color';
         if(!preg_match('/^#[a-f0-9]{6}$/', $rawvalue)) {
             // any non-color (eg. from a previous type) should default to the default
             $rawvalue = $this->config['default'];
         }
         $name = hsc($name);
         $rawvalue = hsc($rawvalue);
-        $html = "<input name=\"$name\" value=\"$rawvalue\" class=\"$class\" type=\"color\" />";
+        $id = !empty($htmlID) ? "id=\"$htmlID\"" : '';
+        $html = "<input name=\"$name\" value=\"$rawvalue\" class=\"$class\" type=\"color\" $id />";
```
Comment (splitbrain) [inline types/Color.php]: Those lines (in all of the files) are starting to get ugly. I wonder if it would be better to switch to a `buildAttributes()` approach where where we use associative arrays to prepare the HTML attributes. It would also do the empty($htmlID) check for us.

File: types/Checkbox.php (hunk 1 above)
Comment (micgro42) [inline types/Checkbox.php]: This is a loop. I only want to give the ID to the first checkbox, all the further checkboxes should not receive an ID. Hence I assign `$htmlID` `null` so that the check `!empty($htmlID)` in the line above fails.

File: types/Color.php (hunk 2 above)
Comment (micgro42) [inline types/Color.php]: I agree. That would make for nicer code and catch/prevent more errors.

File: types/Checkbox.php (hunk 1 above)
Comment (splitbrain) [inline types/Checkbox.php]: ah of course. nevermind.
